- README.md
- pymanopt/manifolds/grassmann.py
- pymanopt/manifolds/stiefel.py
- pymanopt/solvers/__init__.py
- pymanopt/solvers/conjugate_gradient.py
- pymanopt/solvers/particle_swarm.py
I decided to create a PR for this first one rather than just merging it since I'm not sure the implementation is correct. I tested the PSO algorithm in manopt for the dominant eigenvector example, and while it didn't perform too well (being a heuristic and all), it still performed better than the pymanopt variant in the same parameter regime.
BTW, I tried to test PSO on the dominant invariant subspace example as well, but that produced exceptions in the Grassmannian's projector due to incompatible dimensions at https://github.com/nkoep/pymanopt/blob/7e9d3b1d6153aa25f81e49e5cef2df97002fa988/pymanopt/manifolds/grassmann.py#L72
> Particle swarm optimization algorithm

- .travis.yml
See https://github.com/travis-ci/travis-ci/issues/4816
> Add libgfortran to travis.yml

- .travis.yml
Changed blas implementation from ATLAS to openblas in .travis.yml
> Fix travis build for python3

- examples/regression_offset_autograd.py
- examples/regression_offset_theano.py
- pymanopt/core/problem.py
- pymanopt/manifolds/__init__.py
- pymanopt/manifolds/product.py
- pymanopt/manifolds/sphere.py
- pymanopt/solvers/trust_regions.py
- pymanopt/tools/autodiff/_autograd.py
- pymanopt/tools/autodiff/_theano.py
- tests/test_autograd.py
- tests/test_manifold_product.py
- tests/test_theano.py
- todo.md
Still need to fix fallback hessian support in _theano.py when Rop is NotImplemented
> Add product manifold

- .travis.yml
Run tests in separate conda environments
> travis.yml: test in separate conda environments

- examples/low_rank_matrix_approximation.py
- pymanopt/manifolds/fixed_rank.py
- pymanopt/tools/autodiff/_autograd.py
- tests/test_autograd.py
- tests/test_manifold_fixed_rank.py
Now compatible with Theano and Tensorflow backends, however I have not yet had a chance to calculate and implement a correct ehess2rhess method, so currently no support for TrustRegions.
> Simplify fixed rank

- pymanopt/manifolds/__init__.py
- pymanopt/manifolds/complexcircle.py
- pymanopt/manifolds/grassmann.py
- pymanopt/manifolds/manifold.py
- pymanopt/manifolds/oblique.py
- pymanopt/manifolds/sphere.py
- pymanopt/manifolds/stiefel.py
I just remembered that I had this PR queued up for a while. It's a pretty straightforward port from manopt. As usual, unit tests are missing at the moment, but I don't think there's any harm in merging it anyway.
> Add complex circle manifold

- pymanopt/tools/autodiff/_theano.py
- tests/test_theano.py
I fixed the Theano Rop fallback to also work with product manifolds, and thought you might want it. As far as I can tell, the math works out, but I'm not completely sure that bad things won't happen if you have complicated tensor shapes. And the nested list transpose feels a bit hackish. I have tested it by running the test suite with the Rop variant disabled, but please double-check my logic.
> Fix Theano Rop fallback for product manifold

- examples/rotations_example.py
- pymanopt/manifolds/fixed_rank.py
- pymanopt/manifolds/product.py
- pymanopt/solvers/conjugate_gradient.py
- pymanopt/solvers/particle_swarm.py
- pymanopt/solvers/trust_regions.py
- pymanopt/tools/__init__.py
- tests/test_manifold_product.py
This should fix the remaining issues in #49. I'm just leaving this here for now before merging in case we come up with a proper way to fix the commutativity issue with _TangentVector as mentioned in https://github.com/pymanopt/pymanopt/issues/49#issuecomment-385340653.
> Clean up product manifold

- pymanopt/manifolds/psd.py
- tests/test_manifold_positive_definite.py
Following PR #70, this is the PR part which focus on the correction of the distance for positive definite manifold. The part focusing on the update of Travis file is in PR #72.
> Positive Definite manifold distance

- pymanopt/manifolds/rotations.py
Fixes #77.
Signed-off-by: Mihai Capotă <mihai@mihaic.ro>
> Fix compatibility with SciPy 1.3.0

- pymanopt/manifolds/psd.py
Fixed description such that the Y's have full rank.
> descripition of complex psd of fixed rank

- website/README.md
> Fix main repo link in website/README.md

- pymanopt/manifolds/__init__.py
- pymanopt/manifolds/strictly_positive_vectors.py
- tests/test_manifolds/test_strictly_positive_vectors.py
Hello,
I have implemented the manifold of strictly positive vectors which derives from the positive definite matrices. I also implemented the corresponding unit tests.
> Add manifold of strictly positive vectors

- setup.py
> Update python versions in setup script

- TODO.md
- setup.py
> Fix setup.py when no pymanopt dependencies are present

- TODO.md
- examples/dominant_eigenvector.py
- tests/optimizers/test_optimzers.py
This PR adds a test case that runs every optimizer for a few iterations on a simple toy problem to provide a basic integrity check for each solver.
> Add simple end-to-end test case for optimizers

- pymanopt/__init__.py
- pymanopt/autodiff/__init__.py
- pymanopt/autodiff/backends/_autograd.py
- pymanopt/autodiff/backends/_backend.py
- pymanopt/autodiff/backends/_numpy.py
- pymanopt/autodiff/backends/_pytorch.py
- pymanopt/autodiff/backends/_tensorflow.py
- pymanopt/core/problem.py
- tests/backends/_backend_tests.py
- tests/backends/test_numpy.py
- tests/test_problem_backend_interface.py
> Rename autodiff backend methods

- .github/workflows/build_release_package.yml
> Allow tagging releases from version branches

- TODO.md
- pymanopt/manifolds/oblique.py
- pymanopt/manifolds/stiefel.py
- tests/manifolds/test_fixed_rank.py
> Implement Weingarten map for Stiefel manifold

- pymanopt/manifolds/manifold.py
- pymanopt/tools/multi.py
- tests/manifolds/test_symmetric_positive_definite.py
Complete tests for distance for SPD matrices, checking the exponential metric increasing property.
Related to #185.
> Complete tests for SPD matrices, 2nd part

- pymanopt/tools/multi.py
- requirements/base.txt
- setup.py
- tests/manifolds/test_hyperbolic.py
> Add torch to list of optional dependencies

- setup.cfg
> Fix package build config

- .github/workflows/build_documentation.yml
- setup.cfg
> Re-enable build of stable docs
